//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoNote.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoNote.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die about ähnelt.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save ähnelt.
        /// </summary>
        public static string AppBarSave {
            get {
                return ResourceManager.GetString("AppBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die edit picture ähnelt.
        /// </summary>
        public static string AppBarSelectPicture {
            get {
                return ResourceManager.GetString("AppBarSelectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die undo ähnelt.
        /// </summary>
        public static string AppBarUndo {
            get {
                return ResourceManager.GetString("AppBarUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die by Benjamin Sautermeister ähnelt.
        /// </summary>
        public static string ApplicationAuthor {
            get {
                return ResourceManager.GetString("ApplicationAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This app extends the Photos-Hub of Windows Phone 8 to enable a fast and easy functionality to take notes on your pictures or highlight the most important parts. ähnelt.
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Photo Marker ähnelt.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1.0 ähnelt.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contributors ähnelt.
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die apps@bsautermeister.de ähnelt.
        /// </summary>
        public static string FeedbackEmail {
            get {
                return ResourceManager.GetString("FeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading... ähnelt.
        /// </summary>
        public static string InAppStoreLoading {
            get {
                return ResourceManager.GetString("InAppStoreLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are currently no in-app purchases available. Please try again later. ähnelt.
        /// </summary>
        public static string InAppStoreNoProducts {
            get {
                return ResourceManager.GetString("InAppStoreNoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die purchased ähnelt.
        /// </summary>
        public static string InAppStorePurchased {
            get {
                return ResourceManager.GetString("InAppStorePurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die in-app store ähnelt.
        /// </summary>
        public static string InAppStoreTitle {
            get {
                return ResourceManager.GetString("InAppStoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open your library and select an image ähnelt.
        /// </summary>
        public static string Info1 {
            get {
                return ResourceManager.GetString("Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Edit options ähnelt.
        /// </summary>
        public static string Info2 {
            get {
                return ResourceManager.GetString("Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos; ähnelt.
        /// </summary>
        public static string Info3Close {
            get {
                return ResourceManager.GetString("Info3Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select &apos; ähnelt.
        /// </summary>
        public static string Info3Open {
            get {
                return ResourceManager.GetString("Info3Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The photo can be edited instantly... ähnelt.
        /// </summary>
        public static string Info4 {
            get {
                return ResourceManager.GetString("Info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die choose a picture you would like to edit... ähnelt.
        /// </summary>
        public static string InfoChoosePhoto {
            get {
                return ResourceManager.GetString("InfoChoosePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Launching the photo information app could not be started. I&apos;m very sorry! ähnelt.
        /// </summary>
        public static string MessageBoxNoInfo {
            get {
                return ResourceManager.GetString("MessageBoxNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string MessageBoxWarning {
            get {
                return ResourceManager.GetString("MessageBoxWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die more apps ähnelt.
        /// </summary>
        public static string MoreApps {
            get {
                return ResourceManager.GetString("MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die privacy info ähnelt.
        /// </summary>
        public static string PrivacyInfo {
            get {
                return ResourceManager.GetString("PrivacyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rate and review ähnelt.
        /// </summary>
        public static string RateAndReview {
            get {
                return ResourceManager.GetString("RateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LeftToRight ähnelt.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en-US ähnelt.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die share ähnelt.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show picture information ähnelt.
        /// </summary>
        public static string ShowPhotoInfo {
            get {
                return ResourceManager.GetString("ShowPhotoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die support and feedback ähnelt.
        /// </summary>
        public static string SupportAndFeedback {
            get {
                return ResourceManager.GetString("SupportAndFeedback", resourceCulture);
            }
        }
    }
}
